import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h3>This is the home page!</h3>
    </div>
  )
}

export const getServerSideProps = async(ctx)=>{
  return {props: {session: ctx.req.cookies.sid?ctx.req.cookies.sid : null}};
}
