import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ShopKeeper App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h3>Hello,</h3>
      <p>Nexjs, Mongoose is used to create this app. This app is extremely simple. I used session to manage auth, validate operations and stuff.</p>
      <h3>Everything should be wokrking fine!</h3>
      <p>just do npm install or yarn install!</p>
      <p>I would recomend for shopkeeper login, </p>
      <ul>
        <li>user4</li>
        <li>password</li>
      </ul>
      <p>I would recomend for customer login, </p>
      <ul>
        <li>user1</li>
        <li>password</li>
      </ul>


    </div>
  )
}

export const getServerSideProps = async(ctx)=>{
  return {props: {session: ctx.req.cookies.sid?ctx.req.cookies.sid : null}};
}
